FROM python:3.7
USER root

WORKDIR /app
COPY federated-learning-lib /app

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install virtualenv
RUN virtualenv venv
RUN . venv/bin/activate
#RUN pip3 install  -r federated-learning-lib/requirements.txt
RUN pip3 install  -r requirements.txt
RUN pip3 install federated-learning-lib/federated_learning_lib-1.0.5-py3-none-any.whl
RUN pip3 install awscli
RUN pip3 install boto3
ADD edge-demo/aggregator.py aggregator.py
ADD edge-demo/party.py party.py
CMD ["/bin/bash"]
