FROM python:3.7
USER root
RUN ls

WORKDIR /app
COPY . /app

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install virtualenv
RUN virtualenv venv
RUN . venv/bin/activate
RUN pip3 install  -r requirements.txt
RUN pip3 install federated-learning-lib/federated_learning_lib-*-py3-none-any.whl

CMD ["/bin/bash"]
