apiVersion: v1
data:
  mosquitto.conf: |
    persistence true
    persistence_file mosquitto.db
    persistence_location /mosquitto/data
    allow_anonymous true
kind: ConfigMap
metadata:
  name: mosquitto-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mosquitto
        image: docker.io/eclipse-mosquitto:1.6.15
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 1883
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
        resources:
            limits:
              memory: 128Mi
        volumeMounts:
        - name: mqtt-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf 
      volumes:
      - name: mqtt-config
        configMap:
          name: mosquitto-config
---
kind: Service
apiVersion: v1
metadata:
  name: mqtt-tcp
spec:
  type: NodePort
  selector: 
    app: mqtt
  ports:
  - nodePort: 31883
    port: 1883
    targetPort: 1883
---
kind: Service
apiVersion: v1
metadata:
  name: mqtt-tls
spec:
  type: NodePort
  selector:
    app: mqtt    
  ports:
  - nodePort: 31001
    port: 9001
    targetPort: 9001
